# This file contains JS conformance configurations for various possible problems
# with JavaScript.
# See https://github.com/google/closure-compiler/wiki/JS-Conformance-Framework

requirement: {
  type: CUSTOM
  error_message: 'Possible dereference of null value.'
  java_class: 'com.google.javascript.jscomp.ConformanceRules$BanNullDeref'
}

requirement: {
  type: CUSTOM
  error_message: 'Unresolved type which is referenced and known via'
    'forward declarations but not included in the compilation jobs dependencies'
  java_class: 'com.google.javascript.jscomp.ConformanceRules$BanUnresolvedType'
}

requirement: {
  type: CUSTOM
  error_message: 'Global variables must be goog.provided or whitelisted'
  java_class: 'com.google.javascript.jscomp.ConformanceRules$BanGlobalVars'
  whitelist_regexp: '.*_test\\.js'
}

requirement: {
  type: CUSTOM
  error_message: '“this” value is typed as “unknown”'
  java_class: 'com.google.javascript.jscomp.ConformanceRules$BanUnknownThis'
}

requirement: {
  type: CUSTOM
  error_message: 'property reference is typed as “unknown”'
  java_class: 'com.google.javascript.jscomp.ConformanceRules$BanUnknownTypedClassPropsReferences'
}
